channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - binutils_impl_linux-64
  - binutils_linux-64
  - blas
  - bottleneck
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - gcc_impl_linux-64
  - gcc_linux-64
  - gxx_impl_linux-64
  - gxx_linux-64
  - h5py
  - hdf5
  - idna
  - intel-openmp
  - jcc
  - joblib
  - kernel-headers_linux-64
  - ld_impl_linux-64
  - libffi
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nibabel
  - nilearn
  - numexpr
  - openjdk
  - openssl
  - packaging
  - pandas
  - pip
  - pycparser
  - pydicom
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - sysroot_linux-64
  - threadpoolctl
  - tk
  - tzdata
  - urllib3
  - wheel
  - xz
  - zlib
  - pip:
    - antspyx
    - chart-studio
    - cycler
    - dipy
    - fonttools
    - imageio
    - kiwisolver
    - matplotlib
    - networkx
    - numpy
    - patsy
    - pillow
    - plotly
    - psutil
    - pywavelets
    - pyyaml
    - retrying
    - scikit-image
    - statsmodels
    - tenacity
    - tifffile
    - tqdm
    - webcolors
