name: Build and test using conda environment

on:
  push:
    branches: ["*"] 
  pull_request: 
    branches: ["*"]
  schedule:
  # Uses the cron schedule for github actions: runs at midnight on the 1rst and 15th of every month
  #
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  #
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  # │ │ │ │ │
  # │ │ │ │ │
  # │ │ │ │ │
  # * * * * *
    - cron: "0 0 1,15 * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nighres
          environment-file: conda-nighres.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Run build process
        shell: bash -l {0}
        run: |
            ./build.sh

      - name: Run pip install
        run: |
            python3 -m pip install .

      - name: Run smoke tests
        run: make smoke_tests_CI
